on:
  push:
    branches: [beta]
  workflow_dispatch:
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.6
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: sioyek.flatpak
          manifest-path: com.github.ahrm.sioyek.yaml
          cache-key: flatpak-builder-${{ github.sha }}
          branch: beta
